---
- name: Grab K3s and install
  get_url:
    url: https://raw.githubusercontent.com/rancher/k3s/master/install.sh
    dest: /tmp/install.sh
    mode: '0770'

- name: Execute the installer
  shell: /tmp/install.sh --disable traefik

- name: remove the installer
  file: 
    path: /tmp/install.sh
    state: absent

- name: copy the node-token
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: "{{ inventory_dir }}/roles/workernode/files/node-token"
    flat: yes
  with:
    - "{{ inventory_dir }}/roles/workernode/files/node-token"

- name: update kubeconfig
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ primary_user }}/k3s.yaml"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: 0600

- name: Grabe kubeconfig
  fetch:
    src: "/home/{{ primary_user }}/k3s.yaml"