---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install common apps
  apt:
    name: htop,curl,net-tools,nfs-common

- import_tasks: security_tasks.yml

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Add boot line
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^(console=serial0,115200.*)'
    line: 'cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory \1'
    backrefs: yes
  register: cmdline_updated

- name: check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot
  reboot:
    reboot_timeout: 1200
    test_command: mount
  when: reboot_required_file.stat.exists or cmdline_updated.changed

- name: Make sure nfs folders are there
  file:
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_mounts }}"

- name: setup mounts
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    state: mounted
    opts: rw,hard,intr
  with_items: "{{ nfs_mounts }}"

- name: install docker
  shell:
    cmd: curl -sSL https://get.docker.com | sh
  tags:
    - [never,installdocker]

- name: make sure users are in docker
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  with_items:
    - "{{ k3s_users }}"
    - { name: pi }