---
- name: set pi password
  user: 
    name: "{{ ansible_user }}"
    update_password: always
    password: "{{ pi_password | password_hash('sha512') }}"

- name: Setup Users
  user:
    name: "{{ item.name }}"
    state: present
    update_password: always
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
  with_items: "{{ tramski_users }}"

- name: Set authorized key, removing all the authorized keys already set
  authorized_key:
    user: "{{ item.name }}"
    key: '{{ item.key }}'
    state: present
    exclusive: True
  with_items: "{{ tramski_users }}"